# Generated by Django 3.2 on 2021-05-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("auth", "__latest__"), ("authtoken", "__latest__")]

    def generate_superuser(apps, schema_editor):
        from decouple import config
        from django.contrib.auth.models import User

        DJANGO_SU_USERNAME = config("DJANGO_SU_USERNAME", default="admin")
        DJANGO_SU_EMAIL = config("DJANGO_SU_EMAIL", default="admin@example.com")
        DJANGO_SU_PASSWORD = config("DJANGO_SU_PASSWORD", default="@Admin123")

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_USERNAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD,
        )

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
