# Generated by Django 3.2.6 on 2021-09-05 10:41

from django.db import migrations, models
import django.db.models.deletion
import moni.utils.funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(default=moni.utils.funcs.get_str_uuid, max_length=40, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('type', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('webhook', 'Webhook'), ('gotify', 'Gotify')], max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Notifications',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(null=True)),
                ('error', models.TextField(null=True)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_uuid', to='notifications.notifications')),
            ],
            options={
                'verbose_name': 'Notifications History',
                'verbose_name_plural': 'Notifications History',
            },
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['uuid'], name='notificatio_uuid_4a185e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationshistory',
            index=models.Index(fields=['uuid'], name='notificatio_uuid_id_b92ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationshistory',
            index=models.Index(fields=['-timestamp', 'uuid'], name='notificatio_timesta_cc7aad_idx'),
        ),
    ]
