# Generated by Django 3.2.6 on 2021-09-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('webhook', 'Webhook'), ('gotify', 'Gotify'), ('telegram', 'Telegram')], max_length=10),
        ),
    ]
