# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/hadolint/hadolint
    rev: b3555ba9c2bfd9401e79f2f0da68dd1ae38e10c7 # v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles
        description: Runs hadolint Docker image to lint Dockerfiles
        language: docker_image
        types: ["dockerfile"]
        entry: ghcr.io/hadolint/hadolint hadolint
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: Black
        description: The uncompromising Python code formatter
        language_version: python3
        types: [python]
        args:
          - --line-length=130
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        description: A Python utility for sorting imports
        language_version: python3
        types: [python]
        args:
          - --profile=black
          - --line-length=130
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=130
