# Docker compose file for development
services:
  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=moni
    network_mode: host # Port: 5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    network_mode: host # Port: 8080
    healthcheck:
      test: "curl -f localhost:8080 || false"
      interval: 30s
      timeout: 3s
      retries: 10
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    hostname: httpbin
    network_mode: host # Port:
