# Docker compose file for development

version: "3"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=moni
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    ports:
      - 127.0.0.1:8090:8080
    healthcheck:
      test: "curl -f localhost:8080 || false"
      interval: 30s
      timeout: 3s
      retries: 10
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

  gotify:
    image: gotify/server
    container_name: gotify
    hostname: gotify
    ports:
      - 127.0.0.1:8080:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=password
    volumes:
      - "./volumes/gotify:/app/data"
  
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    hostname: httpbin
    ports:
      - 127.0.0.1:8082:80

  api:
    image: python:3.11.3
    command: >
        bash -c "pip install -r requirements.txt -r dev-requirements.txt
        && python manage.py runserver 0.0.0.0:5000"
    working_dir: /app
    container_name: api
    hostname: api
    user: ${HOST_UID}:${HOST_GID}
    env_file:
      - .env
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./backend:/app
    
  moni:
    build: .
    container_name: moni
    hostname: moni
    env_file: docker.env
    ports:
      - 127.0.0.1:5000:8000
    depends_on: 
      - postgres
      - gotify