FROM python:3.13.3 AS base

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    python3-dev \
    libpq-dev \
    libssl-dev \
    libffi-dev \
    rustc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY backend/requirements.txt .

# hadolint ignore=DL3013,DL3042
RUN pip install -U pip setuptools wheel \
    && pip install -r requirements.txt
