# Docker compose file for development

version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=moni
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl -f localhost:8080 || false"
      interval: 30s
      timeout: 3s
      retries: 10
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

  moni-api:
    build:
      context: .
    image: moni
    container_name: moni-api
    hostname: moni-api
    ports:
      - "8000:8000"
    depends_on: 
      - postgres