FROM python:3.12.1 as base

LABEL Github="hibare"

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y build-essential python3-dev libpq-dev libssl-dev libffi-dev rustc

COPY backend/requirements.txt .

RUN pip install -U pip setuptools wheel && pip install -r requirements.txt 
