# Generated by Django 3.2.6 on 2021-09-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifiershistory',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifier_uuid', to='notifiers.notifiers'),
        ),
    ]
