# Generated by Django 3.2.7 on 2021-10-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifiers', '0002_alter_notifiershistory_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifiers',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
