# Generated by Django 3.2.7 on 2021-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifiers', '0003_notifiers_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifiers',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
