# Generated by Django 3.2.7 on 2021-12-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifiers", "0004_alter_notifiers_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifiershistory",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notifiershistory",
            name="status_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
