version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: "postgres_dev"
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  redis_db:
    image: redis:latest
    ports:
      - "6379:6379"
