# Generated by Django 3.2.5 on 2021-07-18 18:21

from django.db import migrations, models
import moni.utils.funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('uuid', models.CharField(default=moni.utils.funcs.get_str_uuid, max_length=40, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('type', models.CharField(choices=[('slack', 'Slack')], max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
