# Generated by Django 3.2.5 on 2021-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['uuid'], name='notificatio_uuid_d5968a_idx'),
        ),
    ]
