# Generated by Django 3.2.6 on 2021-08-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notifications_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField(null=True)),
                ('error', models.TextField(null=True)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_uuid', to='notification.notifications')),
            ],
            options={
                'verbose_name': 'Notifications History',
                'verbose_name_plural': 'Notifications History',
            },
        ),
        migrations.AddIndex(
            model_name='notificationshistory',
            index=models.Index(fields=['uuid'], name='notificatio_uuid_id_49f8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationshistory',
            index=models.Index(fields=['-timestamp', 'uuid'], name='notificatio_timesta_ff6748_idx'),
        ),
    ]
