# Generated by Django 3.2.6 on 2021-08-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20210807_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationshistory',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
