# Generated by Django 3.2 on 2021-05-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('uuid', models.CharField(default='<function uuid4 at 0x7f858bb9ac10>', max_length=33, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True)),
                ('notify_url', models.URLField(null=True)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('interval', models.IntegerField(default=15)),
            ],
        ),
    ]
