# Generated by Django 3.2.6 on 2021-09-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifiers', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='notifiers',
            field=models.ManyToManyField(db_column='uuid', related_name='jobs_notifiers', to='notifiers.Notifiers'),
        ),
    ]
