# Generated by Django 3.2 on 2021-05-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.CharField(default='<function uuid4 at 0x7fbebe92cc10>', max_length=33, primary_key=True, serialize=False),
        ),
    ]
