# Generated by Django 3.2.5 on 2021-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobshistory_error'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobs',
            index=models.Index(fields=['uuid'], name='jobs_jobs_uuid_076788_idx'),
        ),
        migrations.AddIndex(
            model_name='jobshistory',
            index=models.Index(fields=['uuid'], name='jobs_jobshi_uuid_id_a30d59_idx'),
        ),
        migrations.AddIndex(
            model_name='jobshistory',
            index=models.Index(fields=['-timestamp', 'uuid'], name='jobs_jobshi_timesta_69c060_idx'),
        ),
    ]
