# Generated by Django 3.2 on 2021-05-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobs_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Jobs', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.CharField(default='9598d084-6498-4da6-99c9-808c073d71ce', max_length=40, primary_key=True, serialize=False),
        ),
    ]
