# Generated by Django 3.2.5 on 2021-07-28 05:48

import django.contrib.postgres.fields
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210719_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='interval',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='success_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=jobs.models.default_success_status, size=None),
        ),
    ]
