# Generated by Django 3.2 on 2021-05-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210516_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.CharField(default='2c8b3767-4db5-4580-b3fd-f7caa8fc13b6', max_length=40, primary_key=True, serialize=False),
        ),
    ]
