# Generated by Django 3.2 on 2021-05-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobs_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.CharField(default='74a55cf9-43c5-4e11-b652-72b2d942772a', max_length=40, primary_key=True, serialize=False),
        ),
    ]
