# Generated by Django 3.2.7 on 2021-12-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobs_favicon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='favicon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobshistory',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobshistory',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobshistory',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
