# Generated by Django 3.2 on 2021-05-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210516_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='check_redirect',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='success_status',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.CharField(default='049c553d-a973-4dc0-ab5d-6d8ce013fac3', max_length=40, primary_key=True, serialize=False),
        ),
    ]
