# Generated by Django 3.2.9 on 2021-12-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20211205_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='healthy',
            field=models.BooleanField(default=True),
        ),
    ]
