# Generated by Django 4.0 on 2022-01-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_jobs_healthy"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="failure_threshold",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
