# Generated by Django 3.2 on 2021-05-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210516_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.CharField(default='898801c5-8503-4cb6-8ad5-7c8edf050430', max_length=40, primary_key=True, serialize=False),
        ),
    ]
