# Generated by Django 3.2 on 2021-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20210516_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.CharField(default='69a6f8d0-cfdb-404e-8970-0f55fcadea16', max_length=40, primary_key=True, serialize=False),
        ),
    ]
