# Generated by Django 3.2 on 2021-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_jobs_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.CharField(default='88912a22-b2c9-462b-b853-17d780345bca', max_length=40, primary_key=True, serialize=False),
        ),
    ]
