# Generated by Django 3.2 on 2021-06-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_jobs_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.CharField(default='2b4fe98e-9c31-4b02-a0df-42ce7e1d588b', max_length=40, primary_key=True, serialize=False),
        ),
    ]
