# Generated by Django 3.2 on 2021-06-06 16:09

from django.db import migrations, models
import jobs.validators
import moni.utils.funcs


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_jobs_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='notify_url',
            field=models.URLField(null=True, validators=[jobs.validators.apprise_url_validator]),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.CharField(default=moni.utils.funcs.get_str_uuid, max_length=40, primary_key=True, serialize=False),
        ),
    ]
