# Generated by Django 3.2 on 2021-06-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20210606_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='success_status',
        ),
    ]
