# Generated by Django 3.2 on 2021-06-06 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_remove_jobs_success_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='success_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
