# Generated by Django 3.2 on 2021-06-06 16:45

import django.contrib.postgres.fields
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobs_success_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='success_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=jobs.models.default_success_status, size=None),
        ),
    ]
