# Generated by Django 3.2 on 2021-06-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_jobs_success_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField(null=True)),
                ('success', models.BooleanField()),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_history_uuid', to='jobs.jobs')),
            ],
            options={
                'verbose_name': 'Jobs History',
                'verbose_name_plural': 'Jobs History',
            },
        ),
    ]
