# Generated by Django 3.2 on 2021-06-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_jobshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='headers',
            field=models.JSONField(default=dict),
        ),
    ]
