# Generated by Django 3.2.5 on 2021-07-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_jobs_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshistory',
            name='response_time',
            field=models.FloatField(null=True),
        ),
    ]
