# Generated by Django 2.2.7 on 2019-12-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_check_url', models.CharField(max_length=5000)),
                ('mail_recipient', models.CharField(max_length=200)),
                ('slack_endpoint', models.CharField(max_length=5000, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
