# Generated by Django 2.2.7 on 2019-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitors',
            name='mail_recipient',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monitors',
            name='slack_endpoint',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
