
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Go mods
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain version for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"